#!/bin/sh

uci set luci.main.lang=zh_cn

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci set system.@system[0].hostname=Openwrt-x86

uci set fstab.@global[0].anon_mount=1

uci set network.wan.proto='pppoe'
uci set network.wan.username='a13698714869'
uci set network.wan.password='a694869'
uci set network.wan.ifname='eth0'   //我的wan接口是eth0，你要根据自己的路由器情况改
uci set network.wan6.ifname='eth0'

uci set network.lan.ipaddr='192.168.31.2'    //改成你想要默认的管理ip
uci set network.lan.proto='static'          //lan口静态IP方式
uci set network.lan.type='bridge'           //设置桥接
uci set network.lan.ifname='eth1 eth2' //根据自己的路由器情况改Lan口
uci commit

/etc/init.d/network restart

exit 0
