#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci set system.@system[0].hostname=Openwrt-x86
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab


uci set network.wan.proto='pppoe'
uci set network.wan.username='a13698714869'
uci set network.wan.password='a694869'
uci set network.wan.ifname='eth0'   //我的wan接口是eth0，你要根据自己的路由器情况改
uci set network.wan6.ifname='eth0'
uci commit network

uci set network.lan.ipaddr='192.168.31.2'    //改成你想要默认的管理ip
uci set network.lan.proto='static'          //lan口静态IP方式
uci set network.lan.type='bridge'           //设置桥接
uci set network.lan.ifname='eth1 eth2' //根据自己的路由器情况改Lan口
uci commit network

sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

exit 0
